// <auto-generated />
using System;
using DcsOpsBoard.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DcsOpsBoard.Database.Migrations
{
    [DbContext(typeof(OpsBoardDbContext))]
    partial class OpsBoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DcsOpsBoard.Database.Entities.OpsPlanningMission", b =>
                {
                    b.Property<Guid>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Map")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedMissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MissionId");

                    b.ToTable("OpsPlanningMissions");
                });

            modelBuilder.Entity("DcsOpsBoard.Database.Entities.Permission", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "MissionId", "Role");

                    b.HasIndex("MissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DcsOpsBoard.Database.Entities.UserFlights", b =>
                {
                    b.Property<Guid>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("FlightLead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpsPlanningMissionMissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("MissionId");

                    b.HasIndex("OpsPlanningMissionMissionId");

                    b.ToTable("UserFlights");
                });

            modelBuilder.Entity("DcsOpsBoard.Database.Entities.Permission", b =>
                {
                    b.HasOne("DcsOpsBoard.Database.Entities.OpsPlanningMission", null)
                        .WithMany("Permissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DcsOpsBoard.Database.Entities.UserFlights", b =>
                {
                    b.HasOne("DcsOpsBoard.Database.Entities.OpsPlanningMission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DcsOpsBoard.Database.Entities.OpsPlanningMission", null)
                        .WithMany("UserFlights")
                        .HasForeignKey("OpsPlanningMissionMissionId");
                });

            modelBuilder.Entity("DcsOpsBoard.Database.Entities.OpsPlanningMission", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
